### ISSUE TITLE
ripemd160 unsupported

### ISSUE THREAD

**Issue by PhGalaz** [BlockIo/multimerchant-python#1]
I have search for days trying to fix this issue. I can't do nothing related to Bitcoin without it.
This is my code:

import hashlib
from Crypto.Hash import RIPEMD

r = hashlib.new('ripemd160')

this is my log:

Traceback (most recent call last):
  File "error.py", line 4, in <module>
    r = hashlib.new('RIPEMD')
  File "build/bdist.linux-x86_64/egg/hashlib.py", line 87, in __py_new
    elif name in ('SHA512', 'sha512', 'SHA384', 'sha384'):
  File "build/bdist.linux-x86_64/egg/hashlib.py", line 80, in __get_builtin_constructor
    elif name in ('SHA256', 'sha256', 'SHA224', 'sha224'):
ValueError: unsupported hash type

Please help. I'm in Ubuntu 16.04.
Thanks. 

Felipe.

**Comment by doersf** [comment]
Hi

Can you confirm you have the `libssl-dev` package installed on your system?

**Comment by PhGalaz** [comment]
Yes sir, I totally do.
